import { useContext } from "react";
import { LayoutContext } from "../contexts/LayoutContext";
import Head from "next/head";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithubSquare, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import styles from "../styles/AboutPage.module.css";

const AboutPage = () => {
  const { isFixed } = useContext(LayoutContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Brendon Crave Dev | Shopify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${isFixed && styles.main__fixedHeader}`}>
        <h1>Hey there.</h1>
        <div className={styles.aboutImage}></div>
        <h2>About Me</h2>
        <p className={styles.p}>
          I call myself a full-stack creative because I am passionate about so
          many creative forms and love learning new skills that let me pursue
          those forms. In addition to web development my passions include music,
          learning languages, and writing. I currently work as a full-stack web
          developer and freelance Shopify developer.
        </p>
        <h2>My Work</h2>
        <p className={styles.p}>
          Dev Pipeline doubles as a dev shop and a developer mentorship program.
          My work there has included not only web development, but also
          mentorship and curriculum design to help aspiring coders find their
          footing as newcomers to the industry. I also specialize in eCommerce
          development with Shopify, and have previously worked as an audio
          recording engineer and touring musician.
        </p>
        <h2>My Process</h2>
        <p className={styles.p}>
          When I was working as an audio engineer and producer, I learned to
          always "get it right at the source," meaning that every step needs to
          be done with equal respect and attention from beginning to end. I
          approach web development in the exact same way by building web
          applications with the best standards practices in mind.
        </p>
        <div className={styles.callToAction}>
          <h2 className={styles.h2}>Let's work together.</h2>
          <div className={styles.buttons}>
            <Link href="/contact">
              <a>
                <button className={styles.button} id={styles.buttonOne}>
                  Get in Touch
                </button>
              </a>
            </Link>
            <Link href="/myWork">
              <a>
                <button className={styles.button} id={styles.buttonTwo}>
                  See My Work
                </button>
              </a>
            </Link>
          </div>
          <div className={styles.socialLinks}>
            <a
              className={styles.a}
              href="https://www.linkedin.com/in/brendon-crave/"
              target="_blank"
            >
              <FontAwesomeIcon className={styles.icon} icon={faLinkedin} />
            </a>
            <a
              className={styles.a}
              href="https://github.com/bcrave"
              target="_blank"
            >
              <FontAwesomeIcon className={styles.icon} icon={faGithubSquare} />
            </a>
          </div>
        </div>
      </main>
    </div>
  );
};

export default AboutPage;
